config/routes.rb
Rails.application.routes.draw do
  
  root 'auctions#index'
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  #devise_for :users
  
  resources :auctions
  resources :users do
    resources :posts
    end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/auction.rb
class Auction < ApplicationRecord
    # Attributes
    enum status: [:created, :active, :finished, :aborted]
    
    # Relationships
    has_many :participants
    has_many :users, through: :participants
    has_one_attached :image
    
    #callback
    before_create :set_price

    private
    def set_price
        self.price = self.starting_price
    end
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_action :set_auction, only: %i[ show edit update destroy ]

  # GET /auctions or /auctions.json
  def index
    @auctions = current_user.auctions
  end

  # GET /auctions/1 or /auctions/1.json
  def show
    @auction = current_user.auctions.find_by(id: params[:id])
    @owner = current_user
    unless @auction
      flash[:error] = "user unauthorized"
      redirect_to auctions_path
    end
  end

  # GET /auctions/new
  def new
    @auction = Auction.new
  end

  # GET /auctions/1/edit
  def edit
  end

  # POST /auctions or /auctions.json
  def create
    @auction = Auction.new(auction_params)
    current_user.auctions << @auction
    respond_to do |format|
      if @auction.save
        format.html { redirect_to @auction, notice: "Auction was successfully created." }
        format.json { render :show, status: :created, location: @auction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auctions/1 or /auctions/1.json
  def update
    respond_to do |format|
      if @auction.update(auction_params)
        format.html { redirect_to @auction, notice: "Auction was successfully updated." }
        format.json { render :show, status: :ok, location: @auction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auctions/1 or /auctions/1.json
  def destroy
    participants = Paricipant.where(auction_id: @auction.id)
    participants.delete_all
    @auction.destroy
    respond_to do |format|
      format.html { redirect_to auctions_url, notice: "Auction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auction
      @auction = Auction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def auction_params
      params.require(:auction).permit(:title, :description, :expiration_date, :starting_price, :price, :status, :image)
    end
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/views/auctions/_form.html.erb
<%= form_with(model: auction) do |form| %>
  <% if auction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(auction.errors.count, "error") %> prohibited this auction from being saved:</h2>

      <ul>
        <% auction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% if current_user.role == :admin %>
    <div class="field">
      
      <%= form.label :auction_owner %>
      <%= form.collection_select :user_id, @users, :id, :name%>
    </div>
  <%end%>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :expiration_date %>
    <%= form.datetime_select :expiration_date %>
  </div>

  <div class="field">
    <%= form.label :starting_price %>
    <%= form.text_field :starting_price %>
  </div>

  <div class="field">
    <%= form.select(:status, ['active', 'finished', 'aborted'], {include_blank: "Select something"}) %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>        
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
  
<% end %>

app/views/auctions/edit.html.erb
<h1>Editing Auction</h1>

<%= render 'form', auction: @auction %>

<%= link_to 'Show', @auction %> |
<%= link_to 'Back', auctions_path %>

app/views/auctions/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
<h1>Auctions</h1>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>Title</th>
      <th>Description</th>
      <th>Expiration date</th>
      <th>Starting price</th>
      <th>Price</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @auctions.each do |auction| %>
      <tr>
        <td><%= auction.id %></td>
        <td><%= auction.title %></td>
        <td><%= auction.description %></td>
        <td><%= auction.expiration_date %></td>
        <td><%= auction.starting_price %></td>
        <td><%= auction.price %></td>
        <td><%= auction.status %></td>
        <td><%= link_to 'Show', auction %></td>
        <td><%= link_to 'Edit', edit_auction_path(auction) %></td>
        <td><%= link_to 'Destroy', auction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Auction', new_auction_path %>

app/views/auctions/new.html.erb
<h1>New Auction</h1>

<%= render 'form', auction: @auction %>

<%= link_to 'Back', auctions_path %>

app/views/auctions/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @auction.title%></h1>
<% if @auction.image.attached? %>
  <image src="<%=url_for(@auction.image)%> height=150 width=150">
<% end %>
<h2>Acution Details</h2>
<p>
  <strong>Title:</strong>
  <%= @auction.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @auction.description %>
</p>

<p>
  <strong>Expiration date:</strong>
  <%= @auction.expiration_date %>
</p>

<p>
  <strong>Starting price:</strong>
  <%= @auction.starting_price %>
</p>

<p>
  <strong>Price:</strong>
  <%= @auction.price %>
</p>

<p>
  <strong>Status:</strong>
  <%= @auction.status %>
</p>

<p>
  <strong>Owner:</strong>
  <%= "#{@owner.name.capitalize} #{@owner.lastname}" %>
</p>


<%= link_to 'Edit', edit_auction_path(@auction) %> |
<%= link_to 'Back', auctions_path %>