config/routes.rb
Rails.application.routes.draw do
  
  root 'auctions#index'
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  #devise_for :users
  
  resources :auctions
  resources :users do
    resources :posts
    end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :get_user

  # GET /posts or /posts.json
  def index
    @user = User.find_by(id: params[:user_id])
    @posts = @user.posts
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = params[:user_id]    
    respond_to do |format|
      if @post.save
        format.html { redirect_to user_post_path(@user, @post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to user_post_path(@user, @post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to user_posts_path(@user), notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def get_user
      @user = User.find(params[:user_id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:description, :user_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: [@user, @post]) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', user_post_path(@user, @post) %> |
<%= link_to 'Back', user_posts_path(@user) %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.id %></td>
        <td><%= post.description %></td>
        <td><%= link_to 'Show', user_post_path(@user, post) %></td>
        <td><%= link_to 'Edit', edit_user_post_path(@user, post) %></td>
        <td><%= link_to 'Destroy', [@user, post], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_user_post_path(@user) %>
<%= link_to 'Back', users_path%>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', user_posts_path(@user)%>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
  <h1>Detalles de la publicacion</h1>
  <div>
    <strong>Codigo:</strong>
    <%= @post.id %>
  </div>
  <div>
    <strong>Descripcion:</strong>
    <%= @post.description %>
  </div>
  <div>
    <strong>Fecha de creacion:</strong>
    <%= @post.created_at %>
  </div>
  <div>
    <strong>Fecha de actualizacion:</strong>
    <%= @post.updated_at %>
  </div>

<%= link_to 'Edit', edit_user_post_path(@user, @post) %> |
<%= link_to 'Back', user_posts_path(@user) %>